apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.appName }}
  labels:
    app: {{ $.Values.appName }}
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: {{ $.Values.containerPort }}
      nodePort: {{ $.Values.nodePort }}
  selector:
    app: {{ $.Values.appName }}
